hee-ha/hana-heritage-FE

package-lock.json
package.json
src/App.jsx
src/pages/deposit/DepositDetail.jsx
src/pages/deposit/DepositSign1.jsx
src/pages/index.js

- 적금 상품 상세화면
- 적금 상품 가입 약관동의 화면 (1단계)
Resolves: #3 
어떤 변경 사항이 있나요?

적금 상품 상세화면, 약관동의 화면 개발 (#3)

---

src/pages/account-inquiry/AccountCard.jsx
src/pages/account-inquiry/AccountInquiry.jsx

계좌 조회 페이지 추가

---

src/pages/deposit/Deposit.jsx
src/pages/deposit/Depositdetail.jsx
src/pages/saving/Saving.jsx
src/pages/saving/Savingdetail.jsx

- 예금 상품 조회 화면
- 적금 상품 조회 화면
- 예금 계좌 만기일 조회
- 적금 계좌 만기일 조회
어떤 변경 사항이 있나요?

feat:예적금상품_조회_페이지_제작(#10)

---

.idea/workspace.xml
src/App.jsx
src/Nav.js
src/components/Header.jsx
src/pages/deposit/DepositDetail.jsx
src/pages/index.js
src/pages/simple-transaction/AutoTransfer.jsx
src/pages/simple-transaction/SimpleTransaction.jsx
src/pages/simple-transaction/TransferView.jsx
src/pages/simple-transaction/component/Bankbtn.jsx
src/pages/simple-transaction/component/TransferAmount.jsx
src/styles/transaction.css

- 계좌이체 화면
- 이체확인 화면
- 자동이체 화면
어떤 변경 사항이 있나요?

계좌이체 자동이체 페이지 화면 개발

---

src/App.jsx
src/pages/saving/Confirmation.jsx
src/pages/saving/Joinsuccess.jsx
src/pages/saving/Saving.jsx

- 예금 상품 가입 폼 페이지
- 정보 확인 페이지
가입 폼에서 입력 값 넘어옴
- 가입 확정 페이지
Resolves: #(4) 
어떤 변경 사항이 있나요?

feat : 예적금 가입 폼, 정보 확인, 가입 확정 페이지 구현

---

src/pages/deposits/DepositsDetail.jsx

- 개인정보동의 내용
- 입력 폼
- 동의 버튼
> 상담신청 폼 화면 생성
Resolves: #20 
어떤 변경 사항이 있나요?

feat : 상담신청 폼 화면 생성 완료

---

src/pages/account/AccountDetail.jsx
src/pages/deposits/DepositsList.jsx

예적금상품 리스트 조회 화면 버튼 수정
예적금 계좌 정보 조회 화면 변경
어떤 변경 사항이 있나요?
예적금상품 리스트 조회 화면
예적금 계좌 정보 조회 화면 

예적금상품 리스트 조회, 예적금 계좌 정보 조회 CSS 수정

---

src/pages/transfer/TransferHistory.jsx

거래내역페이지 CSS 수정

---

src/pages/deposits/DepositsDetail.jsx
src/pages/deposits/DepositsJoin2.jsx
src/pages/deposits/DepositsJoin3.jsx

#21 
어떤 변경 사항이 있나요?
- DepositsJoin2
- DepositsJoin3
- DepositsJoin4

예적금 가입2, 예적금 가입3, 예적금 가입4 디자인 수정

---

src/pages/deposits/DepositsJoin1.jsx

예적금 가입 시 약관 동의에 스크립트 추가
Resolves: #40 

예적금 가입 시 약관 동의에 스크립트 추가

---

package-lock.json
package.json
src/apis/authService.js
src/apis/axiosInstance.js
src/context/authContext.js
src/hooks/useAuth.js
src/index.js
src/pages/user/Login.jsx
src/utils/auth.js
src/utils/tokenService.js

로그인 및 jwt api 연결

---

src/apis/consulting/addConsultingReservation.js
src/apis/depositsDetail/getDepositsDetail.js
src/pages/deposits/DepositsDetail.jsx

Resolves: #35 
Resolves: #38 
어떤 변경 사항이 있나요?

예적금 상품 상세조회, 상담 신청 폼 등록 api 연결

---

src/App.jsx
src/components/admin/AdminLayout.jsx
src/components/admin/AdminSidebar.jsx
src/pages/admin/AdminHome.jsx
src/pages/admin/ConsultingReview.jsx
src/pages/admin/DepositsPreference.jsx
src/pages/admin/InheritanceReview.jsx
src/pages/admin/Mail.jsx
src/pages/admin/Settlement.jsx
src/pages/index.js

admin 페이지 사이드바 추가 및 라우팅

---

src/components/admin/AdminSidebar.jsx

chore : 네비게이션 메뉴 간격 조정

---

src/components/admin/AdminFooter.jsx
src/components/admin/AdminLayout.jsx
src/components/admin/AdminSidebar.jsx
src/pages/admin/ConsultingReview.jsx

상담 대기 목록 페이지 제작 및 어드민 레이아웃 수정(+푸터추가)

---

src/pages/admin/ConsultingReview.jsx
src/pages/admin/InheritanceReview.jsx
src/pages/admin/InheritanceReviewCard.jsx

feat : 상속 계약 요청 목록 화면 개발

---

src/pages/admin/Mail.jsx

feat : 메일 발송 예약 화면

---

package-lock.json
package.json
src/components/common/Badge/GreenBadge.jsx
src/components/common/Button/GradientButton.jsx
src/components/common/Card/CardWithButton.jsx
src/components/common/Chart/LineChart.jsx
src/components/common/Rating/StarAndLink.jsx
src/pages/admin/ConsultingReview.jsx
src/pages/admin/DepositsPreference.jsx
src/pages/admin/InheritanceReview.jsx
src/pages/admin/InheritanceReviewCard.jsx
src/pages/admin/Mail.jsx

상품 선호도 통계 화면 개발

---

src/Nav.js
yarn.lock

내비게이션바 선택된 메뉴 스타일 적용 로직 추가

---

src/App.jsx
src/apis/customer/getCustomerContact.js
src/apis/sms/reserveSms.js
src/components/admin/AdminSidebar.jsx
src/components/common/Button/GradientButton.jsx
src/components/common/DatePicker/DatePicker.jsx
src/pages/admin/SmsReservation.jsx
src/pages/index.js
yarn.lock

문자 발송 대상 조회 및 예약발송 api 연결

---

src/App.jsx
src/apis/sms/getReservationList.js
src/components/common/Badge/GrayBadge.jsx
src/components/common/Badge/GreenBadge.jsx
src/pages/admin/SmsReservationResult.jsx
src/pages/index.js

메일 발송 여부 리스트 표 화면 추가 및 api 연결

---

src/components/common/Button/GradientButton.jsx
src/components/common/Modal/InheritanceModal.jsx
src/pages/admin/InheritanceReview.jsx
src/pages/admin/InheritanceReviewCard.jsx

상속 계약 서류 검토 화면 추가

---

src/apis/admin/approveLivingTrustContract.js
src/apis/admin/livingTrustContract.js
src/pages/admin/InheritanceReview.jsx
src/pages/admin/InheritanceReviewCard.jsx

신탁 계약 신청 조회, 승인 api

---

src/Nav.js
src/apis/transfer/autoTransfer.js
src/apis/transfer/simpleTransfer.js
src/pages/transfer/AutoTransfer.jsx
src/pages/transfer/SimpleTransfer.jsx
src/pages/transfer/TransferView.jsx

이체기능 API 연결 수정
